@startuml
package dominio{
 class Order implements Serializable {
    private static final long serialVersionUID = -1106285234830970111L;

    private int id;
    private Customer customer;
    private Date date;
    private double subtotal;
    private double tax;
    private double total;
    private String shipType;
    private Date shipDate;
    private String status;
    private Address billingAddress;
    private Address shippingAddress;
    private CCTransaction cc;
    private ArrayList<OrderLine> lines;

    public Order(int id, Customer customer, Date date, Cart cart,            String comment, String shipType, Date shipDate, String status,            Address billingAddress, Address shippingAddress, CCTransaction cc) 
    
    public int getId() 
    public Customer getCustomer() 
    public Date getDate() 
    public double getSubtotal() 
    public double getTax() 
    public double getTotal() 
    public String getShipType() 
    public Date getShipDate() 
    public String getStatus() 
    public Address getBillingAddress() 
    public Address getShippingAddress() 
    public CCTransaction getCC() 
    public ArrayList<OrderLine> getLines() 
}
}
@enduml